#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perpus_Ku
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PerpusKu")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insert_book(_book instance);
    partial void Update_book(_book instance);
    partial void Delete_book(_book instance);
    partial void Insert_user(_user instance);
    partial void Update_user(_user instance);
    partial void Delete_user(_user instance);
    partial void Insert_circulation(_circulation instance);
    partial void Update_circulation(_circulation instance);
    partial void Delete_circulation(_circulation instance);
    partial void Insert_circulation_detail(_circulation_detail instance);
    partial void Update_circulation_detail(_circulation_detail instance);
    partial void Delete_circulation_detail(_circulation_detail instance);
    partial void Insert_classification(_classification instance);
    partial void Update_classification(_classification instance);
    partial void Delete_classification(_classification instance);
    partial void Insert_member(_member instance);
    partial void Update_member(_member instance);
    partial void Delete_member(_member instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Perpus_Ku.Properties.Settings.Default.PerpusKuConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<_book> _books
		{
			get
			{
				return this.GetTable<_book>();
			}
		}
		
		public System.Data.Linq.Table<_user> _users
		{
			get
			{
				return this.GetTable<_user>();
			}
		}
		
		public System.Data.Linq.Table<_circulation> _circulations
		{
			get
			{
				return this.GetTable<_circulation>();
			}
		}
		
		public System.Data.Linq.Table<_circulation_detail> _circulation_details
		{
			get
			{
				return this.GetTable<_circulation_detail>();
			}
		}
		
		public System.Data.Linq.Table<_classification> _classifications
		{
			get
			{
				return this.GetTable<_classification>();
			}
		}
		
		public System.Data.Linq.Table<_member> _members
		{
			get
			{
				return this.GetTable<_member>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_book]")]
	public partial class _book : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string @__isbn;
		
		private string @__title;
		
		private string @__author;
		
		private int @__year;
		
		private string @__publisher;
		
		private int @__classification_id;
		
		private string @__location;
		
		private int @__amount;
		
		private string @__pdf;
		
		private EntitySet<_circulation_detail> @__circulation_details;
		
		private EntityRef<_classification> @__classification;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_isbnChanging(string value);
    partial void On_isbnChanged();
    partial void On_titleChanging(string value);
    partial void On_titleChanged();
    partial void On_authorChanging(string value);
    partial void On_authorChanged();
    partial void On_yearChanging(int value);
    partial void On_yearChanged();
    partial void On_publisherChanging(string value);
    partial void On_publisherChanged();
    partial void On_classification_idChanging(int value);
    partial void On_classification_idChanged();
    partial void On_locationChanging(string value);
    partial void On_locationChanged();
    partial void On_amountChanging(int value);
    partial void On_amountChanged();
    partial void On_pdfChanging(string value);
    partial void On_pdfChanged();
    #endregion
		
		public _book()
		{
			this.@__circulation_details = new EntitySet<_circulation_detail>(new Action<_circulation_detail>(this.attach__circulation_details), new Action<_circulation_detail>(this.detach__circulation_details));
			this.@__classification = default(EntityRef<_classification>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_isbn]", Storage="__isbn", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string _isbn
		{
			get
			{
				return this.@__isbn;
			}
			set
			{
				if ((this.@__isbn != value))
				{
					this.On_isbnChanging(value);
					this.SendPropertyChanging();
					this.@__isbn = value;
					this.SendPropertyChanged("_isbn");
					this.On_isbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_title]", Storage="__title", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string _title
		{
			get
			{
				return this.@__title;
			}
			set
			{
				if ((this.@__title != value))
				{
					this.On_titleChanging(value);
					this.SendPropertyChanging();
					this.@__title = value;
					this.SendPropertyChanged("_title");
					this.On_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_author]", Storage="__author", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string _author
		{
			get
			{
				return this.@__author;
			}
			set
			{
				if ((this.@__author != value))
				{
					this.On_authorChanging(value);
					this.SendPropertyChanging();
					this.@__author = value;
					this.SendPropertyChanged("_author");
					this.On_authorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_year]", Storage="__year", DbType="Int NOT NULL")]
		public int _year
		{
			get
			{
				return this.@__year;
			}
			set
			{
				if ((this.@__year != value))
				{
					this.On_yearChanging(value);
					this.SendPropertyChanging();
					this.@__year = value;
					this.SendPropertyChanged("_year");
					this.On_yearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_publisher]", Storage="__publisher", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string _publisher
		{
			get
			{
				return this.@__publisher;
			}
			set
			{
				if ((this.@__publisher != value))
				{
					this.On_publisherChanging(value);
					this.SendPropertyChanging();
					this.@__publisher = value;
					this.SendPropertyChanged("_publisher");
					this.On_publisherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_classification_id]", Storage="__classification_id", DbType="Int NOT NULL")]
		public int _classification_id
		{
			get
			{
				return this.@__classification_id;
			}
			set
			{
				if ((this.@__classification_id != value))
				{
					this.On_classification_idChanging(value);
					this.SendPropertyChanging();
					this.@__classification_id = value;
					this.SendPropertyChanged("_classification_id");
					this.On_classification_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_location]", Storage="__location", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string _location
		{
			get
			{
				return this.@__location;
			}
			set
			{
				if ((this.@__location != value))
				{
					this.On_locationChanging(value);
					this.SendPropertyChanging();
					this.@__location = value;
					this.SendPropertyChanged("_location");
					this.On_locationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_amount]", Storage="__amount", DbType="Int NOT NULL")]
		public int _amount
		{
			get
			{
				return this.@__amount;
			}
			set
			{
				if ((this.@__amount != value))
				{
					this.On_amountChanging(value);
					this.SendPropertyChanging();
					this.@__amount = value;
					this.SendPropertyChanged("_amount");
					this.On_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_pdf]", Storage="__pdf", DbType="VarChar(50)")]
		public string _pdf
		{
			get
			{
				return this.@__pdf;
			}
			set
			{
				if ((this.@__pdf != value))
				{
					this.On_pdfChanging(value);
					this.SendPropertyChanging();
					this.@__pdf = value;
					this.SendPropertyChanged("_pdf");
					this.On_pdfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_book__circulation_detail", Storage="__circulation_details", ThisKey="_isbn", OtherKey="_isbn")]
		public EntitySet<_circulation_detail> _circulation_details
		{
			get
			{
				return this.@__circulation_details;
			}
			set
			{
				this.@__circulation_details.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_classification__book", Storage="__classification", ThisKey="_classification_id", OtherKey="_id", IsForeignKey=true)]
		public _classification _classification
		{
			get
			{
				return this.@__classification.Entity;
			}
			set
			{
				_classification previousValue = this.@__classification.Entity;
				if (((previousValue != value) 
							|| (this.@__classification.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this.@__classification.Entity = null;
						previousValue._books.Remove(this);
					}
					this.@__classification.Entity = value;
					if ((value != null))
					{
						value._books.Add(this);
						this.@__classification_id = value._id;
					}
					else
					{
						this.@__classification_id = default(int);
					}
					this.SendPropertyChanged("_classification");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach__circulation_details(_circulation_detail entity)
		{
			this.SendPropertyChanging();
			entity._book = this;
		}
		
		private void detach__circulation_details(_circulation_detail entity)
		{
			this.SendPropertyChanging();
			entity._book = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_user]")]
	public partial class _user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int @__user_id;
		
		private string @__identity_number;
		
		private int @__identity_type;
		
		private string @__name;
		
		private string @__username;
		
		private string @__password;
		
		private int @__level;
		
		private EntitySet<_circulation> @__circulations;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_user_idChanging(int value);
    partial void On_user_idChanged();
    partial void On_identity_numberChanging(string value);
    partial void On_identity_numberChanged();
    partial void On_identity_typeChanging(int value);
    partial void On_identity_typeChanged();
    partial void On_nameChanging(string value);
    partial void On_nameChanged();
    partial void On_usernameChanging(string value);
    partial void On_usernameChanged();
    partial void On_passwordChanging(string value);
    partial void On_passwordChanged();
    partial void On_levelChanging(int value);
    partial void On_levelChanged();
    #endregion
		
		public _user()
		{
			this.@__circulations = new EntitySet<_circulation>(new Action<_circulation>(this.attach__circulations), new Action<_circulation>(this.detach__circulations));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_user_id]", Storage="__user_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int _user_id
		{
			get
			{
				return this.@__user_id;
			}
			set
			{
				if ((this.@__user_id != value))
				{
					this.On_user_idChanging(value);
					this.SendPropertyChanging();
					this.@__user_id = value;
					this.SendPropertyChanged("_user_id");
					this.On_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_identity_number]", Storage="__identity_number", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string _identity_number
		{
			get
			{
				return this.@__identity_number;
			}
			set
			{
				if ((this.@__identity_number != value))
				{
					this.On_identity_numberChanging(value);
					this.SendPropertyChanging();
					this.@__identity_number = value;
					this.SendPropertyChanged("_identity_number");
					this.On_identity_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_identity_type]", Storage="__identity_type", DbType="Int NOT NULL")]
		public int _identity_type
		{
			get
			{
				return this.@__identity_type;
			}
			set
			{
				if ((this.@__identity_type != value))
				{
					this.On_identity_typeChanging(value);
					this.SendPropertyChanging();
					this.@__identity_type = value;
					this.SendPropertyChanged("_identity_type");
					this.On_identity_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_name]", Storage="__name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string _name
		{
			get
			{
				return this.@__name;
			}
			set
			{
				if ((this.@__name != value))
				{
					this.On_nameChanging(value);
					this.SendPropertyChanging();
					this.@__name = value;
					this.SendPropertyChanged("_name");
					this.On_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_username]", Storage="__username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string _username
		{
			get
			{
				return this.@__username;
			}
			set
			{
				if ((this.@__username != value))
				{
					this.On_usernameChanging(value);
					this.SendPropertyChanging();
					this.@__username = value;
					this.SendPropertyChanged("_username");
					this.On_usernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_password]", Storage="__password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string _password
		{
			get
			{
				return this.@__password;
			}
			set
			{
				if ((this.@__password != value))
				{
					this.On_passwordChanging(value);
					this.SendPropertyChanging();
					this.@__password = value;
					this.SendPropertyChanged("_password");
					this.On_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_level]", Storage="__level", DbType="Int NOT NULL")]
		public int _level
		{
			get
			{
				return this.@__level;
			}
			set
			{
				if ((this.@__level != value))
				{
					this.On_levelChanging(value);
					this.SendPropertyChanging();
					this.@__level = value;
					this.SendPropertyChanged("_level");
					this.On_levelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_user__circulation", Storage="__circulations", ThisKey="_user_id", OtherKey="_user")]
		public EntitySet<_circulation> _circulations
		{
			get
			{
				return this.@__circulations;
			}
			set
			{
				this.@__circulations.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach__circulations(_circulation entity)
		{
			this.SendPropertyChanging();
			entity._user1 = this;
		}
		
		private void detach__circulations(_circulation entity)
		{
			this.SendPropertyChanging();
			entity._user1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_circulation]")]
	public partial class _circulation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int @__circulation_id;
		
		private int @__member_id;
		
		private System.DateTime @__date_start;
		
		private System.DateTime @__date_finish;
		
		private System.Nullable<System.DateTime> @__date_return;
		
		private System.Nullable<System.DateTime> @__status;
		
		private int @__user;
		
		private EntitySet<_circulation_detail> @__circulation_details;
		
		private EntityRef<_user> @__user1;
		
		private EntityRef<_member> @__member;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_circulation_idChanging(int value);
    partial void On_circulation_idChanged();
    partial void On_member_idChanging(int value);
    partial void On_member_idChanged();
    partial void On_date_startChanging(System.DateTime value);
    partial void On_date_startChanged();
    partial void On_date_finishChanging(System.DateTime value);
    partial void On_date_finishChanged();
    partial void On_date_returnChanging(System.Nullable<System.DateTime> value);
    partial void On_date_returnChanged();
    partial void On_statusChanging(System.Nullable<System.DateTime> value);
    partial void On_statusChanged();
    partial void On_userChanging(int value);
    partial void On_userChanged();
    #endregion
		
		public _circulation()
		{
			this.@__circulation_details = new EntitySet<_circulation_detail>(new Action<_circulation_detail>(this.attach__circulation_details), new Action<_circulation_detail>(this.detach__circulation_details));
			this.@__user1 = default(EntityRef<_user>);
			this.@__member = default(EntityRef<_member>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_circulation_id]", Storage="__circulation_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int _circulation_id
		{
			get
			{
				return this.@__circulation_id;
			}
			set
			{
				if ((this.@__circulation_id != value))
				{
					this.On_circulation_idChanging(value);
					this.SendPropertyChanging();
					this.@__circulation_id = value;
					this.SendPropertyChanged("_circulation_id");
					this.On_circulation_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_member_id]", Storage="__member_id", DbType="Int NOT NULL")]
		public int _member_id
		{
			get
			{
				return this.@__member_id;
			}
			set
			{
				if ((this.@__member_id != value))
				{
					this.On_member_idChanging(value);
					this.SendPropertyChanging();
					this.@__member_id = value;
					this.SendPropertyChanged("_member_id");
					this.On_member_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_date_start]", Storage="__date_start", DbType="Date NOT NULL")]
		public System.DateTime _date_start
		{
			get
			{
				return this.@__date_start;
			}
			set
			{
				if ((this.@__date_start != value))
				{
					this.On_date_startChanging(value);
					this.SendPropertyChanging();
					this.@__date_start = value;
					this.SendPropertyChanged("_date_start");
					this.On_date_startChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_date_finish]", Storage="__date_finish", DbType="Date NOT NULL")]
		public System.DateTime _date_finish
		{
			get
			{
				return this.@__date_finish;
			}
			set
			{
				if ((this.@__date_finish != value))
				{
					this.On_date_finishChanging(value);
					this.SendPropertyChanging();
					this.@__date_finish = value;
					this.SendPropertyChanged("_date_finish");
					this.On_date_finishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_date_return]", Storage="__date_return", DbType="Date")]
		public System.Nullable<System.DateTime> _date_return
		{
			get
			{
				return this.@__date_return;
			}
			set
			{
				if ((this.@__date_return != value))
				{
					this.On_date_returnChanging(value);
					this.SendPropertyChanging();
					this.@__date_return = value;
					this.SendPropertyChanged("_date_return");
					this.On_date_returnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_status]", Storage="__status", DbType="Date")]
		public System.Nullable<System.DateTime> _status
		{
			get
			{
				return this.@__status;
			}
			set
			{
				if ((this.@__status != value))
				{
					this.On_statusChanging(value);
					this.SendPropertyChanging();
					this.@__status = value;
					this.SendPropertyChanged("_status");
					this.On_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_user]", Storage="__user", DbType="Int NOT NULL")]
		public int _user
		{
			get
			{
				return this.@__user;
			}
			set
			{
				if ((this.@__user != value))
				{
					this.On_userChanging(value);
					this.SendPropertyChanging();
					this.@__user = value;
					this.SendPropertyChanged("_user");
					this.On_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_circulation__circulation_detail", Storage="__circulation_details", ThisKey="_circulation_id", OtherKey="_circulation_id")]
		public EntitySet<_circulation_detail> _circulation_details
		{
			get
			{
				return this.@__circulation_details;
			}
			set
			{
				this.@__circulation_details.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_user__circulation", Storage="__user1", ThisKey="_user", OtherKey="_user_id", IsForeignKey=true)]
		public _user _user1
		{
			get
			{
				return this.@__user1.Entity;
			}
			set
			{
				_user previousValue = this.@__user1.Entity;
				if (((previousValue != value) 
							|| (this.@__user1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this.@__user1.Entity = null;
						previousValue._circulations.Remove(this);
					}
					this.@__user1.Entity = value;
					if ((value != null))
					{
						value._circulations.Add(this);
						this.@__user = value._user_id;
					}
					else
					{
						this.@__user = default(int);
					}
					this.SendPropertyChanged("_user1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_member__circulation", Storage="__member", ThisKey="_member_id", OtherKey="_member_id", IsForeignKey=true)]
		public _member _member
		{
			get
			{
				return this.@__member.Entity;
			}
			set
			{
				_member previousValue = this.@__member.Entity;
				if (((previousValue != value) 
							|| (this.@__member.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this.@__member.Entity = null;
						previousValue._circulations.Remove(this);
					}
					this.@__member.Entity = value;
					if ((value != null))
					{
						value._circulations.Add(this);
						this.@__member_id = value._member_id;
					}
					else
					{
						this.@__member_id = default(int);
					}
					this.SendPropertyChanged("_member");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach__circulation_details(_circulation_detail entity)
		{
			this.SendPropertyChanging();
			entity._circulation = this;
		}
		
		private void detach__circulation_details(_circulation_detail entity)
		{
			this.SendPropertyChanging();
			entity._circulation = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_circulation_detail]")]
	public partial class _circulation_detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int @__id;
		
		private int @__circulation_id;
		
		private string @__isbn;
		
		private EntityRef<_book> @__book;
		
		private EntityRef<_circulation> @__circulation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void On_circulation_idChanging(int value);
    partial void On_circulation_idChanged();
    partial void On_isbnChanging(string value);
    partial void On_isbnChanged();
    #endregion
		
		public _circulation_detail()
		{
			this.@__book = default(EntityRef<_book>);
			this.@__circulation = default(EntityRef<_circulation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int _id
		{
			get
			{
				return this.@__id;
			}
			set
			{
				if ((this.@__id != value))
				{
					this.On_idChanging(value);
					this.SendPropertyChanging();
					this.@__id = value;
					this.SendPropertyChanged("_id");
					this.On_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_circulation_id]", Storage="__circulation_id", DbType="Int NOT NULL")]
		public int _circulation_id
		{
			get
			{
				return this.@__circulation_id;
			}
			set
			{
				if ((this.@__circulation_id != value))
				{
					this.On_circulation_idChanging(value);
					this.SendPropertyChanging();
					this.@__circulation_id = value;
					this.SendPropertyChanged("_circulation_id");
					this.On_circulation_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_isbn]", Storage="__isbn", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string _isbn
		{
			get
			{
				return this.@__isbn;
			}
			set
			{
				if ((this.@__isbn != value))
				{
					this.On_isbnChanging(value);
					this.SendPropertyChanging();
					this.@__isbn = value;
					this.SendPropertyChanged("_isbn");
					this.On_isbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_book__circulation_detail", Storage="__book", ThisKey="_isbn", OtherKey="_isbn", IsForeignKey=true)]
		public _book _book
		{
			get
			{
				return this.@__book.Entity;
			}
			set
			{
				_book previousValue = this.@__book.Entity;
				if (((previousValue != value) 
							|| (this.@__book.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this.@__book.Entity = null;
						previousValue._circulation_details.Remove(this);
					}
					this.@__book.Entity = value;
					if ((value != null))
					{
						value._circulation_details.Add(this);
						this.@__isbn = value._isbn;
					}
					else
					{
						this.@__isbn = default(string);
					}
					this.SendPropertyChanged("_book");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_circulation__circulation_detail", Storage="__circulation", ThisKey="_circulation_id", OtherKey="_circulation_id", IsForeignKey=true)]
		public _circulation _circulation
		{
			get
			{
				return this.@__circulation.Entity;
			}
			set
			{
				_circulation previousValue = this.@__circulation.Entity;
				if (((previousValue != value) 
							|| (this.@__circulation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this.@__circulation.Entity = null;
						previousValue._circulation_details.Remove(this);
					}
					this.@__circulation.Entity = value;
					if ((value != null))
					{
						value._circulation_details.Add(this);
						this.@__circulation_id = value._circulation_id;
					}
					else
					{
						this.@__circulation_id = default(int);
					}
					this.SendPropertyChanged("_circulation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_classification]")]
	public partial class _classification : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int @__id;
		
		private string @__name;
		
		private EntitySet<_book> @__books;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void On_nameChanging(string value);
    partial void On_nameChanged();
    #endregion
		
		public _classification()
		{
			this.@__books = new EntitySet<_book>(new Action<_book>(this.attach__books), new Action<_book>(this.detach__books));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int _id
		{
			get
			{
				return this.@__id;
			}
			set
			{
				if ((this.@__id != value))
				{
					this.On_idChanging(value);
					this.SendPropertyChanging();
					this.@__id = value;
					this.SendPropertyChanged("_id");
					this.On_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_name]", Storage="__name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string _name
		{
			get
			{
				return this.@__name;
			}
			set
			{
				if ((this.@__name != value))
				{
					this.On_nameChanging(value);
					this.SendPropertyChanging();
					this.@__name = value;
					this.SendPropertyChanged("_name");
					this.On_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_classification__book", Storage="__books", ThisKey="_id", OtherKey="_classification_id")]
		public EntitySet<_book> _books
		{
			get
			{
				return this.@__books;
			}
			set
			{
				this.@__books.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach__books(_book entity)
		{
			this.SendPropertyChanging();
			entity._classification = this;
		}
		
		private void detach__books(_book entity)
		{
			this.SendPropertyChanging();
			entity._classification = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_member]")]
	public partial class _member : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int @__member_id;
		
		private string @__identity_number;
		
		private int @__identity_type;
		
		private string @__name;
		
		private System.DateTime @__registration_date;
		
		private EntitySet<_circulation> @__circulations;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_member_idChanging(int value);
    partial void On_member_idChanged();
    partial void On_identity_numberChanging(string value);
    partial void On_identity_numberChanged();
    partial void On_identity_typeChanging(int value);
    partial void On_identity_typeChanged();
    partial void On_nameChanging(string value);
    partial void On_nameChanged();
    partial void On_registration_dateChanging(System.DateTime value);
    partial void On_registration_dateChanged();
    #endregion
		
		public _member()
		{
			this.@__circulations = new EntitySet<_circulation>(new Action<_circulation>(this.attach__circulations), new Action<_circulation>(this.detach__circulations));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_member_id]", Storage="__member_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int _member_id
		{
			get
			{
				return this.@__member_id;
			}
			set
			{
				if ((this.@__member_id != value))
				{
					this.On_member_idChanging(value);
					this.SendPropertyChanging();
					this.@__member_id = value;
					this.SendPropertyChanged("_member_id");
					this.On_member_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_identity_number]", Storage="__identity_number", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string _identity_number
		{
			get
			{
				return this.@__identity_number;
			}
			set
			{
				if ((this.@__identity_number != value))
				{
					this.On_identity_numberChanging(value);
					this.SendPropertyChanging();
					this.@__identity_number = value;
					this.SendPropertyChanged("_identity_number");
					this.On_identity_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_identity_type]", Storage="__identity_type", DbType="Int NOT NULL")]
		public int _identity_type
		{
			get
			{
				return this.@__identity_type;
			}
			set
			{
				if ((this.@__identity_type != value))
				{
					this.On_identity_typeChanging(value);
					this.SendPropertyChanging();
					this.@__identity_type = value;
					this.SendPropertyChanged("_identity_type");
					this.On_identity_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_name]", Storage="__name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string _name
		{
			get
			{
				return this.@__name;
			}
			set
			{
				if ((this.@__name != value))
				{
					this.On_nameChanging(value);
					this.SendPropertyChanging();
					this.@__name = value;
					this.SendPropertyChanged("_name");
					this.On_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_registration_date]", Storage="__registration_date", DbType="Date NOT NULL")]
		public System.DateTime _registration_date
		{
			get
			{
				return this.@__registration_date;
			}
			set
			{
				if ((this.@__registration_date != value))
				{
					this.On_registration_dateChanging(value);
					this.SendPropertyChanging();
					this.@__registration_date = value;
					this.SendPropertyChanged("_registration_date");
					this.On_registration_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="_member__circulation", Storage="__circulations", ThisKey="_member_id", OtherKey="_member_id")]
		public EntitySet<_circulation> _circulations
		{
			get
			{
				return this.@__circulations;
			}
			set
			{
				this.@__circulations.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach__circulations(_circulation entity)
		{
			this.SendPropertyChanging();
			entity._member = this;
		}
		
		private void detach__circulations(_circulation entity)
		{
			this.SendPropertyChanging();
			entity._member = null;
		}
	}
}
#pragma warning restore 1591
